---
# ovnkube-node-dpu-host
# daemonset version 3
# starts node daemons for ovn, each in a separate container
# it is run on all nodes
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ovnkube-node-dpu-host
  # namespace set up by install
  namespace: ovn-kubernetes
  annotations:
    kubernetes.io/description: |
      This DaemonSet launches the ovn-kubernetes networking components for worker nodes.
spec:
  selector:
    matchLabels:
      app: ovnkube-node-dpu-host
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ovnkube-node-dpu-host
        name: ovnkube-node-dpu-host
        component: network
        type: infra
        kubernetes.io/os: "linux"
    spec:
      priorityClassName: "system-cluster-critical"
      serviceAccountName: ovnkube-node
      hostNetwork: true
      dnsPolicy: Default
      hostPID: true
      containers:
      
      - name: ovnkube-node
        image: "registry.core.syscallx86.com/ovn-kubernetes:v1.2.0"
        imagePullPolicy: "IfNotPresent"
        
        command: ["/root/ovnkube.sh", "ovn-node"]

        securityContext:
          runAsUser: 0
          privileged: true
          

        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        # Common mounts
        # for the iptables wrapper
        - mountPath: /host
          name: host-slash
          readOnly: true
        - mountPath: /var/run/dbus/
          name: host-var-run-dbus
          readOnly: true
        - mountPath: /var/lib/kubelet
          name: host-kubelet
          readOnly: true
        - mountPath: /var/log/ovn-kubernetes/
          name: host-var-log-ovnkube
          # We mount our socket here
        - mountPath: /var/run/ovn-kubernetes
          name: host-var-run-ovn-kubernetes
        # CNI related mounts which we take over
        - mountPath: /opt/cni/bin
          name: host-opt-cni-bin
        - mountPath: /etc/cni/net.d
          name: host-etc-cni-netd
        - mountPath: /var/run/netns
          name: host-netns
          mountPropagation: Bidirectional
        - mountPath: /run/systemd/private
          name: run-systemd
          subPath: private
          readOnly: true
        # ovnkube-node dpu-host mounts
        - mountPath: /var/run/ovn
          name: var-run-ovn

        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: OVN_DAEMONSET_VERSION
          value: "1.2.0"
        - name: OVNKUBE_LOGLEVEL
          value: "4"
        - name: OVNKUBE_LOGFILE_MAXSIZE
          value: "100"
        - name: OVNKUBE_LOGFILE_MAXBACKUPS
          value: "5"
        - name: OVNKUBE_LOGFILE_MAXAGE
          value: "5"
        - name: OVN_NET_CIDR
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: net_cidr
        - name: OVN_SVC_CIDR
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: svc_cidr
        - name: K8S_APISERVER
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: k8s_apiserver
        - name: OVN_MTU
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: mtu
        - name: OVN_ROUTABLE_MTU
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: routable_mtu
              optional: true
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OVN_GATEWAY_MODE
          value: "local"
        - name: OVN_GATEWAY_OPTS
          value: ""
        - name: OVN_HYBRID_OVERLAY_ENABLE
          value: ""
        - name: OVN_ADMIN_NETWORK_POLICY_ENABLE
          value: ""
        - name: OVN_EGRESSIP_ENABLE
          value: ""
        - name: OVN_EGRESSIP_HEALTHCHECK_PORT
          value: ""
        - name: OVN_EGRESSSERVICE_ENABLE
          value: ""
        - name: OVN_HYBRID_OVERLAY_NET_CIDR
          value: ""
        - name: OVN_DISABLE_SNAT_MULTIPLE_GWS
          value: ""
        - name: OVN_DISABLE_FORWARDING
          value: ""
        - name: OVN_ENCAP_PORT
          value: ""
        - name: OVN_DISABLE_PKT_MTU_CHECK
          value: ""
        - name: OVN_NETFLOW_TARGETS
          value: ""
        - name: OVN_SFLOW_TARGETS
          value: ""
        - name: OVN_IPFIX_TARGETS
          value: ""
        - name: OVN_IPFIX_SAMPLING
          value: ""
        - name: OVN_IPFIX_CACHE_MAX_FLOWS
          value: ""
        - name: OVN_IPFIX_CACHE_ACTIVE_TIMEOUT
          value: ""
        - name: OVN_V4_JOIN_SUBNET
          value: ""
        - name: OVN_V6_JOIN_SUBNET
          value: ""
        - name: OVN_V4_MASQUERADE_SUBNET
          value: ""
        - name: OVN_V6_MASQUERADE_SUBNET
          value: ""
        - name: OVN_MULTICAST_ENABLE
          value: ""
        - name: OVN_UNPRIVILEGED_MODE
          value: "no"
        - name: OVN_EX_GW_NETWORK_INTERFACE
          value: ""
        - name: OVN_ENABLE_OVNKUBE_IDENTITY
          value: "false"
        - name: OVN_NETWORK_QOS_ENABLE
          value: ""
        - name: OVNKUBE_NODE_MODE
          value: "dpu-host"
        - name: OVNKUBE_NODE_MGMT_PORT_NETDEV
          value: ""
        - name: OVN_HOST_NETWORK_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: host_network_namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name

        readinessProbe:
          exec:
            command: ["/usr/bin/ovn-kube-util", "readiness-probe", "-t", "ovnkube-node"]
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 60
      
      nodeSelector:
        kubernetes.io/os: "linux"
        k8s.ovn.org/dpu-host: ""
      volumes:
      # Common volumes
      - name: host-var-run-dbus
        hostPath:
          path: /var/run/dbus
      - name: host-kubelet
        hostPath:
          path: /var/lib/kubelet
      - name: host-var-log-ovnkube
        hostPath:
          path: /var/log/ovn-kubernetes
      - name: host-var-run-ovn-kubernetes
        hostPath:
          path: /var/run/ovn-kubernetes
      - name: host-opt-cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: host-etc-cni-netd
        hostPath:
          path: /etc/cni/net.d
      - name: host-slash
        hostPath:
          path: /
      - name: host-netns
        hostPath:
          path: /var/run/netns
      - name: run-systemd
        hostPath:
          path: /run/systemd
      - name: var-run-ovn
        emptyDir: {}

      tolerations:
      - operator: "Exists"
