- name: Set global variables
  set_fact:
    domain: "core.syscallx86.com"
    global_subnet: "4"
    ipaserver: "idm"
    jumpserver: "jump"
    ldapbase: "dc=core,dc=syscallx86,dc=com"
    svcadmin: "admin"
    adminpwd: "admin123"
    template: "basevm"
    template_dir: "/data/vms/templates"
    vms_dir: "/data/vms"
    mem: "4G"
    vcpus: "8"
    user_password: "admin123"
    virbr: "40"
    libvirtnet: "class"
    build_snapshot: "ready-to-build"
    kubernetes_version: "1.35.0"
