- hosts: localhost
  become: true
  connection: local
  gather_facts: no
  tasks:

  - name: Set create loadbalancer env variables
    ansible.builtin.template:
       src: templates/loadbalancer.j2
       dest: include/_setup_vars.yaml

