- name: Set vm local variables
  set_fact:
    virbr: "41"
    netsuffix: "8" 
    hostname: "wks-b78bca-0000"
    rootvg_size: 30
    vcpus: 2
    podnetwork: "10.38.0.0/16"
    svcnetwork: "10.49.0.0/16"
    clusterdom: "cluster.local"
    bridge_name: "br-ex"
    iface: "enp1s0"
    ip_address: "10.4.1.8"
    k8s_role: "worker"
    srv_name: "k8s-0001"
    srv_port: 6443