---
- name: Deploy krew
  become: true
  become_user: "{{ item.name }}"
  shell: (
          set -x; cd "$(mktemp -d)" &&
          OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
          ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
          KREW="krew-${OS}_${ARCH}" &&
          curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
          tar zxvf "${KREW}.tar.gz" &&
          ./"${KREW}" install krew
          )

- name: Create bash bash_profile
  become: true
  become_user: "{{ item.name }}"
  shell: touch ~/.bash_profile
  ignore_errors: true
  
- name: Add krew to path
  become: true
  become_user: "{{ item.name }}"
  ansible.builtin.blockinfile:
    path: ~/.bash_profile
    marker: "# {mark} ANSIBLE MANAGED KREW BLOCK"
    block: |
      export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH" 

- name: Install kubectl krew plugins
  become: true
  become_user: "{{ item.name }}"
  shell: export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH" && kubectl krew install ns

- name: Add alias for kubectl ns
  become: true
  become_user: "{{ item.name }}"
  ansible.builtin.lineinfile: 
    path: ~/.bash_profile
    line: "alias kubens='kubectl-ns'"

- name: Add alias for oc
  become: true
  become_user: "{{ item.name }}"
  ansible.builtin.lineinfile: 
    path: ~/.bash_profile
    line: "alias oc='kubectl'"

- name: Add alias for get token
  become: true
  become_user: "{{ item.name }}"
  ansible.builtin.lineinfile: 
    path: ~/.bash_profile
    line: "alias token='kubectl create token dashboard-admin --namespace dashboard'"