- name: Set vm local variables
  set_fact:
    virbr: "41"
    peerbr: "49"
    libvirtpeernet: "class"
    netsuffix: "252" 
    hostname: "lbc-b78bca-00002"
    rootvg_size: 30
    vcpus: 2
    podnetwork: "10.38.0.0/16"
    svcnetwork: "10.49.0.0/16"
    clusterdom: "cluster.local"
    bridge_name: "br-ex"
    iface: "enp1s0"
    ip_address: "10.4.1.252"
    k8s_role: "lbc"
    srv_name: "k8s-0001"
    srv_port: 6443